Gas test2
Kiyo510/GAS_TEST pull request #2
Opened 2022-01-20 13:37 UTC by Kiyo510

2022-01-20 14:36 UTC, Kiyo510 commented
aaaaaa

2022-01-21 15:23 UTC, SanoKiyo approved these changes
LGTM！

2022-01-22 02:39 UTC, SanoKiyo approved these changes
LGTM

2022-01-22 02:58 UTC, SanoKiyo requested changes
Not ok.

2022-01-22 03:05 UTC, SanoKiyo approved these changes
LGTM

2022-01-22 04:02 UTC, SanoKiyo requested changes
komentodesu

2022-01-22 04:06 UTC, SanoKiyo approved these changes
LGTM!

2022-01-22 14:29 UTC, merged